### ISSUE TITLE
[Bug]: `ImportError: cannot import name 'GenericHtmxView' from 'handyhelpers.views.htmx'`

### ISSUE THREAD

**Issue by KGB33** [SpokaneTech/SpokaneTech_Py#43]
### Descriription

`django-handyhelpers` removed `GenericHtmxView` in `0.3.16` (See [here](https://github.com/davidslusser/django-handyhelpers/pull/118)).

### Expected behavior

`python manage.py migrate` completes successfully.

### Steps to reproduce the behavior

```bash
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt -r requirements/dev.txt
cd src
python manage.py migrate
```

Note:
```
$ pip freeze | rg hand
django-handyhelpers==0.3.16
```

### Relevant log output

```shell
$ python manage.py migrate
Traceback (most recent call last):
  File "/home/kgb33/Code/SpokaneTech_Py/main/src/manage.py", line 22, in <module>
    main()
  File "/home/kgb33/Code/SpokaneTech_Py/main/src/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 516, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/current-system/sw/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/kgb33/Code/SpokaneTech_Py/main/src/spokanetech/urls.py", line 24, in <module>
    path("", include("web.urls")),
             ^^^^^^^^^^^^^^^^^^^
  File "/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/current-system/sw/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/kgb33/Code/SpokaneTech_Py/main/src/web/urls.py", line 1, in <module>
    from web import views
  File "/home/kgb33/Code/SpokaneTech_Py/main/src/web/views.py", line 8, in <module>
    from handyhelpers.views.htmx import GenericHtmxView
ImportError: cannot import name 'GenericHtmxView' from 'handyhelpers.views.htmx' (/home/kgb33/Code/SpokaneTech_Py/main/.venv/lib/python3.12/site-packages/handyhelpers/views/htmx.py)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joeriddles** [comment]
cc @davidslusser

**Comment by davidslusser** [comment]
Thanks for catching that; I totally thought it was set to django-handyhelpers~=0.3 which should keep us at the latest 0.3.z version. FYI, there is a new version I hope to complete today that add a new htmx cbv to what it should have been in the first place. If anyone's interested in a walk through and usage examples let me know.
